// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8aATGBvBVCIQzV1aPPBFWMP5ZorbOCfw',
    appId: '1:176891083985:web:59e37e6086155084bc99f0',
    messagingSenderId: '176891083985',
    projectId: 'salesiq-f0530',
    authDomain: 'salesiq-f0530.firebaseapp.com',
    storageBucket: 'salesiq-f0530.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGhuuea7SUgHl6wfRY33dQI80wRtmPtOo',
    appId: '1:176891083985:android:cdedd91dc48f5e4fbc99f0',
    messagingSenderId: '176891083985',
    projectId: 'salesiq-f0530',
    storageBucket: 'salesiq-f0530.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvFaSlqbmQE4Y2cfq-9CQsZbUpaZx87Mg',
    appId: '1:176891083985:ios:e190a6e446c465d1bc99f0',
    messagingSenderId: '176891083985',
    projectId: 'salesiq-f0530',
    storageBucket: 'salesiq-f0530.firebasestorage.app',
    iosBundleId: 'com.example.salesiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvFaSlqbmQE4Y2cfq-9CQsZbUpaZx87Mg',
    appId: '1:176891083985:ios:e190a6e446c465d1bc99f0',
    messagingSenderId: '176891083985',
    projectId: 'salesiq-f0530',
    storageBucket: 'salesiq-f0530.firebasestorage.app',
    iosBundleId: 'com.example.salesiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8aATGBvBVCIQzV1aPPBFWMP5ZorbOCfw',
    appId: '1:176891083985:web:afa2c96c87c715afbc99f0',
    messagingSenderId: '176891083985',
    projectId: 'salesiq-f0530',
    authDomain: 'salesiq-f0530.firebaseapp.com',
    storageBucket: 'salesiq-f0530.firebasestorage.app',
  );

}