// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmokioyIUugGTLyOZCr3zLvngL-UqGrL4',
    appId: '1:408592089006:web:98ef4e5fb918931a97523f',
    messagingSenderId: '408592089006',
    projectId: 'salesiq-47533',
    authDomain: 'salesiq-47533.firebaseapp.com',
    storageBucket: 'salesiq-47533.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmokioyIUugGTLyOZCr3zLvngL-UqGrL4',
    appId: '1:408592089006:android:98ef4e5fb918931a97523f',
    messagingSenderId: '408592089006',
    projectId: 'salesiq-47533',
    storageBucket: 'salesiq-47533.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmokioyIUugGTLyOZCr3zLvngL-UqGrL4',
    appId: '1:408592089006:ios:98ef4e5fb918931a97523f',
    messagingSenderId: '408592089006',
    projectId: 'salesiq-47533',
    storageBucket: 'salesiq-47533.firebasestorage.app',
    iosBundleId: 'com.example.salesiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmokioyIUugGTLyOZCr3zLvngL-UqGrL4',
    appId: '1:408592089006:macos:98ef4e5fb918931a97523f',
    messagingSenderId: '408592089006',
    projectId: 'salesiq-47533',
    storageBucket: 'salesiq-47533.firebasestorage.app',
    iosBundleId: 'com.example.salesiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmokioyIUugGTLyOZCr3zLvngL-UqGrL4',
    appId: '1:408592089006:windows:98ef4e5fb918931a97523f',
    messagingSenderId: '408592089006',
    projectId: 'salesiq-47533',
    authDomain: 'salesiq-47533.firebaseapp.com',
    storageBucket: 'salesiq-47533.firebasestorage.app',
  );
}
